name: Sandertest
favicon: null
layout_spectrum: 0.8694564569741488
typography_spectrum: 0.5909119311254472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de007a'
    - '#ffffff'
    - '#fadfee'
    - '#f29fcd'
    - '#ea5fab'
  brandStrength: 0.9749303415883332
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.43525858852081
purpose: []
