name: Sandertest
favicon: null
layout_spectrum: 0.87971
typography_spectrum: 0.32575
title: Hello World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de007a'
    - '#ffffff'
    - '#fadfee'
    - '#f29fcd'
    - '#ea5fab'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
